.TH "C:/Users/cbanw/GitHub/Spectrum Health Systems/Tingen-Development/src/obj/Debug/.NETFramework,Version=v4.8.AssemblyAttributes.cs" 3 "Tingen_development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cbanw/GitHub/Spectrum Health Systems/Tingen-Development/src/obj/Debug/.NETFramework,Version=v4.8.AssemblyAttributes.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Tingen_development from the source code\&.
