.TH "C:/Users/cbanw/GitHub/Spectrum Health Systems/Tingen-Development/src/DocumentationTesting.cs" 3 "Tingen_development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/cbanw/GitHub/Spectrum Health Systems/Tingen-Development/src/DocumentationTesting.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTingen_development\&.DocumentationTesting\fP"
.br
.ti -1c
.RI "class \fBTingen_development\&.DocumentationTesting\&.ExampleClass\fP"
.br
.RI "Every class and member should have a one sentence summary describing its purpose\&. "
.ti -1c
.RI "class \fBTingen_development\&.MainClass\fP"
.br
.RI "A summary about this class\&. "
.ti -1c
.RI "class \fBTingen_development\&.DerivedClass\fP"
.br
.ti -1c
.RI "interface \fBTingen_development\&.ITestInterface\fP"
.br
.RI "This interface would describe all the methods in its contract\&. "
.ti -1c
.RI "class \fBTingen_development\&.ImplementingClass\fP"
.br
.ti -1c
.RI "class \fBTingen_development\&.InheritOnlyReturns\fP"
.br
.RI "This class shows hows you can 'inherit' the doc comments from one method in another method\&. "
.ti -1c
.RI "class \fBTingen_development\&.InheritAllButRemarks\fP"
.br
.RI "This class shows an example ofsharing comments across methods\&. "
.ti -1c
.RI "class \fBTingen_development\&.GenericClass< T >\fP"
.br
.RI "This is a generic class\&. "
.ti -1c
.RI "class \fBTingen_development\&.ParamsAndParamRefs\fP"
.br
.RI "This shows examples of typeparamref and typeparam tags\&. "
.ti -1c
.RI "class \fBTingen_development\&.TaggedLibrary\&.Math\fP"
.br
.RI "The main \fR\fBMath\fP\fP class\&. Contains all methods for performing basic math functions\&. 
.PD 0
.IP "\(bu" 2
Add Addition Operation  
.IP "\(bu" 2
Subtract Subtraction Operation  
.IP "\(bu" 2
Multiply Multiplication Operation  
.IP "\(bu" 2
Divide Division Operation  
.PP
"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBTingen_development\fP"
.br
.ti -1c
.RI "namespace \fBTingen_development\&.TaggedLibrary\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Tingen_development from the source code\&.
