.TH "Tingen_development.DerivedClass" 3 "Tingen_development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tingen_development.DerivedClass \-  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBTingen_development\&.MainClass\fP\&.
.SH "Detailed Description"
.PP 


.SH "Author"
.PP 
Generated automatically by Doxygen for Tingen_development from the source code\&.
