.TH "Tingen_development" 3 "Tingen_development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tingen_development
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDerivedClass\fP"
.br
.ti -1c
.RI "class \fBDocumentationTesting\fP"
.br
.ti -1c
.RI "class \fBGenericClass\fP"
.br
.RI "This is a generic class\&. "
.ti -1c
.RI "class \fBImplementingClass\fP"
.br
.ti -1c
.RI "class \fBInheritAllButRemarks\fP"
.br
.RI "This class shows an example ofsharing comments across methods\&. "
.ti -1c
.RI "class \fBInheritOnlyReturns\fP"
.br
.RI "This class shows hows you can 'inherit' the doc comments from one method in another method\&. "
.ti -1c
.RI "interface \fBITestInterface\fP"
.br
.RI "This interface would describe all the methods in its contract\&. "
.ti -1c
.RI "class \fBMainClass\fP"
.br
.RI "A summary about this class\&. "
.ti -1c
.RI "class \fBParamsAndParamRefs\fP"
.br
.RI "This shows examples of typeparamref and typeparam tags\&. "
.ti -1c
.RI "class \fBTingen_development\fP"
.br
.RI "The entry class for Tingen\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Tingen_development from the source code\&.
