.TH "Tingen_development.GenericClass< T >" 3 "Tingen_development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tingen_development.GenericClass< T > \- This is a generic class\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This is a generic class\&. 

This example shows how to specify the GenericClass<T> type as a cref attribute\&. In generic classes and methods, you'll often want to reference the generic type, or the type parameter\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Tingen_development from the source code\&.
