.TH "Tingen_development.MainClass" 3 "Tingen_development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tingen_development.MainClass \- A summary about this class\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBTingen_development\&.DerivedClass\fP\&.
.SH "Detailed Description"
.PP 
A summary about this class\&. 

These remarks would explain more about this class\&. In this example, these comments also explain the general information about the derived class\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Tingen_development from the source code\&.
