.TH "Tingen_development.InheritOnlyReturns" 3 "Tingen_development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tingen_development.InheritOnlyReturns \- This class shows hows you can 'inherit' the doc comments from one method in another method\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBMyParentMethod\fP (bool x)"
.br
.RI "In this example, this summary is only visible for this method\&. "
.ti -1c
.RI "static bool \fBMyChildMethod\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class shows hows you can 'inherit' the doc comments from one method in another method\&. 

You can inherit all comments, or only a specific tag, represented by an xpath expression\&. 
.SH "Member Function Documentation"
.PP 
.SS "static bool Tingen_development\&.InheritOnlyReturns\&.MyParentMethod (bool x)\fR [static]\fP"

.PP
In this example, this summary is only visible for this method\&. 
.PP
\fBReturns\fP
.RS 4
A boolean
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Tingen_development from the source code\&.
