.TH "Tingen_development.DocumentationTesting.ExampleClass" 3 "Tingen_development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tingen_development.DocumentationTesting.ExampleClass \- Every class and member should have a one sentence summary describing its purpose\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBAdd\fP (int left, int right)"
.br
.RI "Adds two integers and returns the result\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBLabel\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Every class and member should have a one sentence summary describing its purpose\&. 

You can expand on that one sentence summary to provide more information for readers\&. In this case, the \fR\fBExampleClass\fP\fP provides different C# elements to show how you would add documentation comments for most elements in a typical class\&. 
.PP
The remarks can add multiple paragraphs, so you can write detailed information for developers that use your work\&. You should add everything needed for readers to be successful\&. This class contains examples for the following: 
.PP
Summary This should provide a one sentence summary of the class or member\&.   Remarks This is typically a more detailed description of the class or member   para The para tag separates a section into multiple paragraphs   list Provides a list of terms or elements   returns, param Used to describe parameters and return values   value Used to describe properties  exception Used to describe exceptions that may be thrown   c, cref, see, seealso These provide code style and links to other documentation elements   example, code These are used for code examples   
.PP
The list above uses the 'table' style\&. You could also use the 'bullet' or 'number' style\&. Neither would typically use the 'term' element\&. 
.br
 Note: paragraphs are double spaced\&. Use the \fIbr\fP tag for single spaced lines\&. 
.SH "Member Function Documentation"
.PP 
.SS "static int Tingen_development\&.DocumentationTesting\&.ExampleClass\&.Add (int left, int right)\fR [static]\fP"

.PP
Adds two integers and returns the result\&. 
.PP
\fBReturns\fP
.RS 4
The sum of two integers\&. 
.RE
.PP
\fBParameters\fP
.RS 4
\fIleft\fP The left operand of the addition\&. 
.br
\fIright\fP The right operand of the addition\&. 
.RE
.PP
.PP
.PP
.nf
int c = Math\&.Add(4, 5);
if (c > 10)
{
    Console\&.WriteLine(c);
}
.fi
.PP
 
.PP
\fBExceptions\fP
.RS 4
\fISystem\&.OverflowException\fP Thrown when one parameter is \fBMaxValue\fP and the other is greater than 0\&. Note that here you can also use  to point a web page instead\&. 
.RE
.PP
\fBExampleClass\fP for a list of all the tags in these examples\&. 
.PP
\fBSee also\fP
.RS 4
\fBExampleClass\&.Label\fP
.PP
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "string Tingen_development\&.DocumentationTesting\&.ExampleClass\&.Label\fR [get]\fP, \fR [set]\fP"
The \fRLabel\fP property represents a label for this instance\&. 
.PP
The \fBLabel\fP is a \fRstring\fP that you use for a label\&. 
.PP
Note that there isn't a way to provide a 'cref' to each accessor, only to the property itself\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Tingen_development from the source code\&.
