.TH "Tingen_development.Tingen_development" 3 "Tingen_development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tingen_development.Tingen_development \- The entry class for Tingen\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits WebService\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBGetVersion\fP ()"
.br
.RI "Returns the current version of Tingen\&. "
.ti -1c
.RI "OptionObject2015 \fBRunScript\fP (OptionObject2015 sentOptionObject, string sentScriptParameter)"
.br
.RI "Starts the Tingen web service\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static string \fBAssemblyName\fP = Assembly\&.GetExecutingAssembly()\&.GetName()\&.Name\fR [get, set]\fP"
.br
.RI "Assembly name for log files\&. "
.ti -1c
.RI "static string \fBTingenVersion\fP = Assembly\&.GetExecutingAssembly()\&.GetName()\&.Version\&.ToString()\fR [get, set]\fP"
.br
.RI "The current version of Tingen\&. "
.in -1c
.SH "Detailed Description"
.PP 
The entry class for Tingen\&. 


.IP "\(bu" 2
This class is designed to be static, and \fIshould not be modified\fP\&.
.br

.IP "\(bu" 2
The heavy lifting is done in the Outpost31
.PP
.PP
project\&. 
.SH "Member Function Documentation"
.PP 
.SS "string Tingen_development\&.Tingen_development\&.GetVersion ()"

.PP
Returns the current version of Tingen\&. 
.IP "\(bu" 2
Required by Avatar\&.
.br

.IP "\(bu" 2
\fIShould not be modified\fP\&. 
.PP
.PP
\fBReturns\fP
.RS 4
The current version of Tingen\&.
.RE
.PP

.SS "OptionObject2015 Tingen_development\&.Tingen_development\&.RunScript (OptionObject2015 sentOptionObject, string sentScriptParameter)"

.PP
Starts the Tingen web service\&. 
.PP
\fBParameters\fP
.RS 4
\fIsentOptionObject\fP The \fIOptionObject\fP  sent from Avatar\&.
.br
\fIsentScriptParameter\fP The \fIScript Parameter\fP  sent from Avatar\&.
.RE
.PP
.PP
.IP "\(bu" 2
Required by Avatar\&.
.br

.IP "\(bu" 2
\fIShould not be modified\fP
.br

.IP "\(bu" 2
The majority of work is done in the Outpost31
.PP
.PP
project\&. 
.PP
\fBReturns\fP
.RS 4
The finalized \fIOptionObject\fP  to myAvatar\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "string Tingen_development\&.Tingen_development\&.AssemblyName = Assembly\&.GetExecutingAssembly()\&.GetName()\&.Name\fR [static]\fP, \fR [get]\fP, \fR [set]\fP"

.PP
Assembly name for log files\&. 
.IP "\(bu" 2
Define the assembly name here so it can be used to write log files throughout the class\&. 
.PP

.SS "string Tingen_development\&.Tingen_development\&.TingenVersion = Assembly\&.GetExecutingAssembly()\&.GetName()\&.Version\&.ToString()\fR [static]\fP, \fR [get]\fP, \fR [set]\fP"

.PP
The current version of Tingen\&. 
.IP "\(bu" 2
Both \fBGetVersion()\fP and \fBRunScript()\fP need the current version number\&. 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Tingen_development from the source code\&.
