.TH "Tingen_development.DocumentationTesting" 3 "Tingen_development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tingen_development.DocumentationTesting
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExampleClass\fP"
.br
.RI "Every class and member should have a one sentence summary describing its purpose\&. "
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Tingen_development from the source code\&.
