.TH "Tingen_development.ParamsAndParamRefs" 3 "Tingen_development" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tingen_development.ParamsAndParamRefs \- This shows examples of typeparamref and typeparam tags\&.  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static T \fBGetGenericValue< T >\fP (T para)"
.br
.RI "The GetGenericValue method\&. "
.in -1c
.SH "Detailed Description"
.PP 
This shows examples of typeparamref and typeparam tags\&. 
.SH "Member Function Documentation"
.PP 
.SS "static T Tingen_development\&.ParamsAndParamRefs\&.GetGenericValue< T > (T para)\fR [static]\fP"

.PP
The GetGenericValue method\&. This sample shows how to specify the GetGenericValue method as a cref attribute\&. The parameter and return value are both of an arbitrary type, \fIT\fP  

.SH "Author"
.PP 
Generated automatically by Doxygen for Tingen_development from the source code\&.
